### ISSUE TITLE
IHM - Retour en cas d'erreur de soumission du formulaire de commande

### ISSUE THREAD

**Issue by AnaelMobilia** [RobinPoulet/nourriture-terrestre#13]
Hello,

Si on ouvre la page du formulaire de commande, qu'on le remplit et qu'au moment de le soumettre on a un problème (réseau ou côté serveur), on à l'impression que rien ne se passe en IHM.

Suggestion : mettre une pop-up qui donne le retour d'erreur.

A+

**Comment by RobinPoulet** [comment]
@AnaelMobilia Tu peux me donner une suggestion pour pouvoir tester ce cas de figure en dév please 🙏🏻

**Comment by AnaelMobilia** [comment]
Modifier [l'url appelée pour ton appel ajax](https://github.com/RobinPoulet/nourriture-terrestre/blob/main/js/index.js#L7).

Au final, c'est rajouter un bloc error du type 
```javascript
    error: function (request, status, error) {
        alert(request.responseText);
    }
```

Je pars du principe [qu'un timeout est considéré comme une erreur côté ajax](https://api.jquery.com/jQuery.ajax/)

**Comment by RobinPoulet** [comment]
👍🏻

**Comment by RobinPoulet** [comment]
👍🏻 👍🏻
